# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Welcome to Colab!
"""

s = input("Enter 3 real number (separated by space): ")
s = s.split()
a = float(s[0])
b = float(s[1])
c = float(s[2])
print(f"a = {a}, b = {b}, c = {c}")

n = int(input("Enter a positive integer: "))
print(n)

s = 0 # bien so de luu tong
# nhap code cua ban vao day
for i in range(n + 1):
  s += i
print(f"The sum of 1 to {n} is {s}")